// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a caption for user-generated content.
 *
 * - `generateUgcCaption`: Generates a short, engaging caption for a user's post.
 * - `UgcCaptionInput`: The input type for the function.
 * - `UgcCaptionOutput`: The output type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const UgcCaptionInputSchema = z.object({
  productName: z.string().describe('The name of the product in the image/video.'),
  category: z.string().describe('The category of the product (e.g., Pottery, Jewelry).'),
  region: z.string().describe('The region where the craft originates (e.g., Rajasthan, India).'),
  language: z.string().describe('The language for the caption (e.g., "Hindi", "English").'),
});
export type UgcCaptionInput = z.infer<typeof UgcCaptionInputSchema>;

const UgcCaptionOutputSchema = z.object({
  caption: z.string().describe("A short, engaging, social-media-style caption."),
});
export type UgcCaptionOutput = z.infer<typeof UgcCaptionOutputSchema>;

export async function generateUgcCaption(input: UgcCaptionInput): Promise<UgcCaptionOutput> {
  return generateUgcCaptionFlow(input);
}

const ugcCaptionPrompt = ai.definePrompt({
  name: 'ugcCaptionPrompt',
  input: { schema: UgcCaptionInputSchema },
  output: { schema: UgcCaptionOutputSchema },
  prompt: `You are an expert social media manager for an artisan marketplace. Your task is to write a short, engaging caption for a user's post in the specified language: {{{language}}}.

The user is sharing a photo of their new "{{productName}}". This craft is a type of {{category}} from {{region}}.

Generate a caption that is one sentence long. It should be positive, appreciative, and feel authentic. End the caption with a relevant emoji.

Examples (if English):
- "Loving my new handmade treasure from Rajasthan! ✨"
- "Bringing a piece of Varanasi's heritage into my home. ❤️"
- "The details on this piece are just breathtaking. 😍"

Do not use hashtags. Just provide the caption text.
`,
});

const generateUgcCaptionFlow = ai.defineFlow(
  {
    name: 'generateUgcCaptionFlow',
    inputSchema: UgcCaptionInputSchema,
    outputSchema: UgcCaptionOutputSchema,
  },
  async input => {
    const { output } = await ugcCaptionPrompt(input);
    return output!;
  }
);
