// This is an autogenerated file from Firebase Studio.
'use client';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import Image from "next/image";
import { useLanguage } from "@/hooks/use-language";

const stories = [
    {
        title: "The Zapotec Pottery of Oaxaca",
        region: "Mexico",
        content: "Discover the ancient techniques of Zapotec pottery, a tradition passed down through generations in the valleys of Oaxaca. Each piece is shaped by hand and fired in open-air pits, embedding the spirit of the earth into the clay.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        imageUrl: "https://picsum.photos/seed/zapotec/400/225"
    },
    {
        title: "Appalachian Woodworking",
        region: "USA",
        content: "In the heart of the Appalachian mountains, artisans transform native hardwoods into functional art. This tradition honors the natural beauty of the wood, celebrating simplicity, craftsmanship, and a deep connection to the forest.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        imageUrl: "https://picsum.photos/seed/appalachia/400/225"
    },
    {
        title: "The Art of Kundan in Jaipur",
        region: "India",
        content: "Jaipur, the 'Pink City', is home to the royal art of Kundan jewelry. This intricate method involves setting polished gemstones into a gold foil base, creating pieces of breathtaking beauty that once adorned royalty.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        imageUrl: "https://picsum.photos/seed/kundan/400/225"
    },
    {
        title: "Japanese Kintsugi",
        region: "Japan",
        content: "Kintsugi, or 'golden joinery', is the Japanese art of repairing broken pottery with lacquer dusted or mixed with powdered gold, silver, or platinum. It treats breakage and repair as part of the history of an object, rather than something to disguise.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        imageUrl: "https://picsum.photos/seed/kintsugi/400/225"
    },
    {
        title: "Moroccan Zellige Tilework",
        region: "Morocco",
        content: "Zellige is a style of mosaic tilework made from individually chiseled geometric tiles set into a plaster base. This art form is one of the main characteristics of Moroccan architecture and is used to ornament walls, ceilings, and floors.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        imageUrl: "https://picsum.photos/seed/zellige/400/225"
    },
    {
        title: "Peruvian Retablos",
        region: "Peru",
        content: "Peruvian retablos are intricate, portable shrines holding detailed miniature scenes of religious, historical, or everyday events. These colorful dioramas are a vibrant form of Andean folk art, passed down through families.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        imageUrl: "https://picsum.photos/seed/retablos/400/225"
    }
]

export default function CulturePage() {
    const { translate } = useLanguage();
    return (
        <div className="container mx-auto px-4 py-8 md:px-6">
            <header className="mb-8 text-center">
                <h1 className="font-headline text-4xl font-bold">{translate('Cultural Heritage Stories')}</h1>
                <p className="mt-2 text-lg text-muted-foreground">
                    {translate('Explore the origins and stories behind the crafts.')}
                </p>
            </header>
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
                {stories.map(story => (
                    <Card key={story.title}>
                         <CardContent className="p-0">
                            <div className="aspect-video w-full overflow-hidden rounded-t-lg">
                                <Image src={story.imageUrl} alt={story.title} width={400} height={225} className="object-cover" data-ai-hint="culture region"/>
                            </div>
                        </CardContent>
                        <CardHeader>
                            <CardTitle className="font-headline text-xl">{translate(story.title)}</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p className="text-sm text-muted-foreground">{translate(story.content)}</p>
                        </CardContent>
                    </Card>
                ))}
            </div>
        </div>
    );
}