// This is an autogenerated file from Firebase Studio.
export const communityPosts = [
    {
      id: "ugc-1",
      userName: "Priya S.",
      imageId: "ugc-image-1",
      productId: "prod-3", // Kundan Meenakari Necklace
      likes: 124,
      comments: 12,
      timeAgo: "2d",
    },
    {
      id: "ugc-2",
      userName: "Michael B.",
      imageId: "ugc-image-2",
      productId: "prod-1", // Blue Pottery Vase
      likes: 88,
      comments: 5,
      timeAgo: "5d",
    },
    {
      id: "ugc-3",
      userName: "Aisha K.",
      imageId: "ugc-image-3",
      productId: "prod-8", // Kashmiri Pashmina Shawl
      likes: 231,
      comments: 25,
      timeAgo: "1w",
    },
    {
      id: "ugc-4",
      userName: "Tom H.",
      imageId: "ugc-image-4",
      productId: "prod-2", // Sheesham Wood Spice Box
      likes: 72,
      comments: 8,
      timeAgo: "1w",
    },
    {
      id: "ugc-5",
      userName: "Sofia R.",
      imageId: "ugc-image-5",
      productId: "prod-7", // Silver Jhumka Earrings
      likes: 156,
      comments: 18,
      timeAgo: "2w",
    },
    {
      id: "ugc-6",
      userName: "David L.",
      imageId: "ugc-image-6",
      productId: "prod-10", // Kutch Lippan Art
      likes: 99,
      comments: 9,
      timeAgo: "3w",
    }
];
