import type { Artisan, Product, Review } from '@/lib/types';

export const artisans: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Riya Sharma',
    location: 'Varanasi, Uttar Pradesh',
    email: 'riya.sharma@artisanai.com',
    story: 'From the ghats of Varanasi, Riya Sharma weaves magic into silk sarees. A tradition passed down through generations, her Banarasi sarees are known for their intricate brocades and fine silk.',
    profileImage: 'artisan-portrait-1',
    bannerImage: 'artisan-banner-1',
    verified: true,
  },
  {
    id: 'artisan-2',
    name: 'Arjun Singh',
    location: 'Jaipur, Rajasthan',
    email: 'arjun.singh@artisanai.com',
    story: 'Arjun Singh is a master of miniature painting, a delicate art form that flourished in the royal courts of Rajasthan. His works depict epic tales and courtly life with mineral and vegetable-based colors on paper.',
    profileImage: 'artisan-portrait-2',
    bannerImage: 'artisan-banner-2',
    verified: true,
  },
   {
    id: 'artisan-3',
    name: 'Priya Patel',
    location: 'Jaipur, Rajasthan',
    email: 'priya.patel@artisanai.com',
    story: 'Priya is a master of Kundan jewelry, a traditional form of Indian gemstone jewelry. Her intricate designs blend royal heritage with contemporary aesthetics, creating heirloom pieces that are both bold and elegant.',
    profileImage: 'artisan-portrait-3',
    bannerImage: 'artisan-banner-3',
    verified: true,
  },
  {
    id: 'artisan-4',
    name: 'Meera Desai',
    location: 'Kutch, Gujarat',
    email: 'meera.desai@artisanai.com',
    story: 'Meera Desai is an expert in Bandhani, a traditional tie-dye textile. Her vibrant sarees and dupattas, created by plucking the cloth with the fingernails into many tiny bindings, are a celebration of Gujarati culture.',
    profileImage: 'artisan-portrait-4',
    bannerImage: 'artisan-banner-4',
    verified: true,
  },
  {
    id: 'artisan-5',
    name: 'Sameer Khan',
    location: 'Srinagar, Jammu & Kashmir',
    email: 'sameer.khan@artisanai.com',
    story: 'Sameer Khan continues the legacy of Kashmiri Pashmina weaving. His shawls, known for their softness and intricate Sozni embroidery, are a testament to the timeless craftsmanship of the valley.',
    profileImage: 'artisan-portrait-5',
    bannerImage: 'artisan-banner-5',
    verified: false,
  },
  {
    id: 'artisan-6',
    name: 'Anjali Devi',
    location: 'Bishnupur, West Bengal',
    email: 'anjali.devi@artisanai.com',
    story: 'Anjali Devi is a skilled artisan of Terracotta pottery from the heart of West Bengal. She molds river clay into beautiful sculptures and potteries, reflecting the folk traditions of her region.',
    profileImage: 'artisan-portrait-6',
    bannerImage: 'artisan-banner-6',
    verified: true,
  },
  {
    id: 'artisan-7',
    name: 'Vikram Reddy',
    location: 'Channapatna, Karnataka',
    email: 'vikram.reddy@artisanai.com',
    story: 'Vikram carries on the 200-year-old tradition of Channapatna toys, a unique form of woodworking using soft ivory wood and vibrant, non-toxic lacquer.',
    profileImage: 'artisan-portrait-7',
    bannerImage: 'artisan-banner-7',
    verified: true,
  },
  {
    id: 'artisan-8',
    name: 'Fatima Ahmed',
    location: 'Lucknow, Uttar Pradesh',
    email: 'fatima.a@artisanai.com',
    story: 'Fatima is a master of Chikankari, the delicate and artfully done hand embroidery from Lucknow. Her ethereal creations on fine cotton and muslin are sought after for their elegance.',
    profileImage: 'artisan-portrait-8',
    bannerImage: 'artisan-banner-8',
    verified: false,
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Blue Pottery Vase',
    artisanId: 'artisan-2',
    price: 4500,
    category: 'Pottery',
    productType: 'Vase',
    images: ['product-pottery-1', 'product-pottery-2'],
    description: 'A stunning blue pottery vase from Jaipur, hand-painted with traditional floral motifs. A perfect centerpiece that brings a touch of Rajasthani royalty to your home.',
    makingProcess: "Crafted from a unique mix of quartz stone powder, powdered glass, and fuller's earth. The iconic cobalt blue dye is used for the vibrant coloring before it is low-fired.",
    region: 'Rajasthan',
    material: 'Stoneware clay',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-2',
    name: 'Sheesham Wood Spice Box',
    artisanId: 'artisan-7',
    price: 3200,
    category: 'Woodwork',
    productType: 'Bowl',
    images: ['product-woodwork-1', 'product-woodwork-2'],
    description: 'A hand-carved spice box made from durable Sheesham wood (Indian Rosewood). Features intricate carvings and a rotating lid, making it both a functional kitchen tool and a decorative piece.',
    makingProcess: 'A single block of Sheesham wood is selected and meticulously hand-carved by skilled artisans. The piece is then sanded for a smooth finish and polished with natural oils to bring out the rich grain of the wood.',
    region: 'Uttar Pradesh',
    material: 'Sheesham',
    sustainability: 'Sustainably Sourced',
  },
  {
    id: 'prod-3',
    name: 'Kundan Meenakari Necklace',
    artisanId: 'artisan-3',
    price: 25000,
    category: 'Jewelry',
    productType: 'Necklace',
    images: ['product-jewelry-1', 'product-jewelry-2'],
    description: "An exquisite Kundan Meenakari necklace set, featuring uncut polki stones and intricate enamel work on the reverse side. A masterpiece of Jaipur's royal jewelry tradition.",
    makingProcess: 'Highly refined gold is hammered into a frame, and uncut gemstones are set into it. The reverse side is then intricately enameled (Meenakari) with vibrant colors, a process that can take weeks.',
    region: 'Rajasthan',
    material: 'Gold',
  },
  {
    id: 'prod-4',
    name: 'Banarasi Silk Saree',
    artisanId: 'artisan-1',
    price: 45000,
    category: 'Textiles',
    productType: 'Saree',
    images: ['product-textiles-1', 'product-textiles-2'],
    description: 'A luxurious, hand-woven Banarasi silk saree with intricate gold zari work. This opulent textile is a symbol of Indian heritage, perfect for weddings and grand occasions.',
    makingProcess: 'Woven on a handloom, this saree takes anywhere from 15 days to a month to create. The process involves designing the pattern, punching it onto cards, and then meticulously weaving silk and zari threads together.',
    region: 'Uttar Pradesh',
    material: 'Silk',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-5',
    name: 'Bishnupur Terracotta Plate',
    artisanId: 'artisan-6',
    price: 800,
    category: 'Pottery',
    productType: 'Plate',
    images: ['product-pottery-3', 'product-pottery-4'],
    description: 'A decorative terracotta plate from Bishnupur, famed for its intricate carvings depicting scenes from Indian epics. A beautiful piece of wall art that tells a story.',
    makingProcess: 'Made from rich alluvial clay from the Ganges delta, this plate is hand-molded and then sun-dried. The detailed narrative scenes are carved before the plate is fired in a kiln, giving it its characteristic reddish-brown color.',
    region: 'West Bengal',
    material: 'Terracotta clay',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-6',
    name: 'Sandalwood Elephant',
    artisanId: 'artisan-7',
    price: 8500,
    category: 'Woodwork',
    productType: 'Sculpture',
    images: ['product-woodwork-3', 'product-woodwork-4'],
    description: "A finely carved sandalwood elephant, showcasing the incredible skill of Karnataka's artisans. The natural fragrance of sandalwood makes this a multi-sensory art piece.",
    makingProcess: "Sourced from government-managed forests, the sandalwood is carved with extreme precision using specialized tools. The intricate details, or 'jaali' work, are a hallmark of this craft.",
    region: 'Karnataka',
    material: 'Sandalwood',
    sustainability: 'Sustainably Sourced',
  },
  {
    id: 'prod-7',
    name: 'Silver Jhumka Earrings',
    artisanId: 'artisan-3',
    price: 7500,
    category: 'Jewelry',
    productType: 'Earrings',
    images: ['product-jewelry-3', 'product-jewelry-4'],
    description: 'Classic silver jhumka earrings with delicate filigree work and tiny dangling beads. These timeless bell-shaped earrings add a touch of ethnic grace to any outfit.',
    makingProcess: 'Silver wires are twisted and shaped by hand to create the intricate filigree patterns. The dome shape is formed, and small silver beads are attached to complete the traditional jhumka design.',
    region: 'Odisha',
    material: 'Silver',
  },
  {
    id: 'prod-8',
    name: 'Kashmiri Pashmina Shawl',
    artisanId: 'artisan-5',
    price: 35000,
    category: 'Textiles',
    productType: 'Shawl',
    images: ['product-textiles-3', 'product-textiles-4'],
    description: "An incredibly soft and warm hand-woven Pashmina shawl from Kashmir. This luxurious accessory features intricate 'sozni' embroidery, a testament to the artisan's skill.",
    makingProcess: 'The fine wool is hand-spun from the fleece of the Changthangi goat. It is then woven on a traditional loom, and finally, a master artisan spends months doing the fine needlework embroidery.',
    region: 'Jammu & Kashmir',
    material: 'Wool',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-9',
    name: 'Chikankari Kurta',
    artisanId: 'artisan-8',
    price: 6800,
    category: 'Textiles',
    productType: 'Kurta',
    images: ['product-textiles-5', 'product-textiles-6'],
    description: 'An elegant white cotton kurta featuring delicate Chikankari hand-embroidery from Lucknow. Lightweight and breathable, it is perfect for sophisticated summer wear.',
    makingProcess: 'The design is first block-printed onto the fabric. The artisan then uses a needle and thread to create various intricate stitches over the printed pattern. The finished piece is washed to remove the initial print.',
    region: 'Uttar Pradesh',
    material: 'Cotton',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-10',
    name: 'Kutch Lippan Art',
    artisanId: 'artisan-4',
    price: 900,
    category: 'Pottery',
    productType: 'Wall Hanging',
    images: ['product-pottery-5', 'product-pottery-6'],
    description: 'A traditional mud and mirror-work (Lippan Kaam) wall art from the Kutch region of Gujarat. The intricate geometric patterns and sparkling mirrors create a stunning visual effect.',
    makingProcess: 'A mixture of clay and camel dung is spread on a wooden board. While the mixture is still wet, intricate patterns are created with fingers, and small mirrors (aabhla) are embedded into the design.',
    region: 'Gujarat',
    material: 'Earthenware clay',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-11',
    name: 'Brass Dhokra Bull',
    artisanId: 'artisan-6',
    price: 5200,
    category: 'Jewelry',
    productType: 'Sculpture',
    images: ['product-jewelry-5', 'product-jewelry-6'],
    description: 'A tribal Dhokra art sculpture of a bull, crafted using the lost-wax casting technique. This ancient method gives each piece a unique, rustic, and antique look.',
    makingProcess: 'A clay core is made, which is then covered by a layer of beeswax. The wax is carved with designs. This is covered with more clay, and molten brass is poured in, melting the wax and taking its place.',
    region: 'Chhattisgarh',
    material: 'Brass',
    sustainability: 'Recycled Materials',
  },
  {
    id: 'prod-12',
    name: 'Bamboo Weave Basket',
    artisanId: 'artisan-7',
    price: 2200,
    category: 'Woodwork',
    productType: 'Basket',
    images: ['product-woodwork-5', 'product-woodwork-6'],
    description: 'A beautifully hand-woven bamboo basket from the state of Assam. Strong, lightweight, and eco-friendly, it can be used for storage, as a planter, or as a decorative item.',
    makingProcess: 'Bamboo is harvested, cut into strips of varying thickness, and then woven by hand into intricate patterns. The process requires skill and precision to create a sturdy and well-finished product.',
    region: 'Assam',
    material: 'Bamboo',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-13',
    name: 'Porcelain Serving Bowl',
    artisanId: 'artisan-2',
    price: 3800,
    category: 'Pottery',
    productType: 'Bowl',
    images: ['product-pottery-7', 'product-pottery-8'],
    description: 'A delicate porcelain serving bowl, featuring a minimalist design with a clear glaze. Its translucent quality and elegant shape make it a modern dining essential.',
    makingProcess: 'Fine porcelain clay is wheel-thrown and trimmed. After bisque firing, a clear glaze is applied, and it is high-fired to achieve its signature vitrified, non-porous state.',
    region: 'Goa',
    material: 'Porcelain clay',
  },
  {
    id: 'prod-14',
    name: 'Rosewood Pen Stand',
    artisanId: 'artisan-7',
    price: 1800,
    category: 'Woodwork',
    productType: 'Furniture',
    images: ['product-woodwork-7', 'product-woodwork-8'],
    description: 'An elegant pen stand crafted from rich, dark Rosewood. Its smooth finish and sturdy design make it a sophisticated addition to any desk.',
    makingProcess: 'A solid piece of Rosewood is shaped and drilled. It is then sanded multiple times to achieve a silky-smooth surface and finished with a protective coat of lacquer to enhance its natural beauty.',
    region: 'Kerala',
    material: 'Rosewood',
    sustainability: 'Sustainably Sourced',
  },
  {
    id: 'prod-15',
    name: 'Copper Link Bracelet',
    artisanId: 'artisan-3',
    price: 500,
    category: 'Jewelry',
    productType: 'Bracelet',
    images: ['product-jewelry-7', 'product-jewelry-8'],
    description: 'A stylish and contemporary bracelet made of pure copper links. Believed to have health benefits, this piece combines modern design with traditional material.',
    makingProcess: 'Copper wire is shaped into individual links, which are then soldered together. The bracelet is polished to a high shine and treated to prevent rapid tarnishing.',
    region: 'Maharashtra',
    material: 'Copper',
  },
  {
    id: 'prod-16',
    name: 'Linen Summer Scarf',
    artisanId: 'artisan-8',
    price: 2900,
    category: 'Textiles',
    productType: 'Scarf',
    images: ['product-textiles-7', 'product-textiles-8'],
    description: 'A lightweight and breathable linen scarf, perfect for summer. Hand-dyed in a beautiful indigo, it features a simple, elegant design.',
    makingProcess: 'High-quality linen fabric is hand-dyed using natural indigo pigments. The process involves multiple dips to achieve the desired depth of color. The scarf is then washed and softened.',
    region: 'West Bengal',
    material: 'Linen',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-17',
    name: 'Earthenware Cooking Pot',
    artisanId: 'artisan-6',
    price: 1500,
    category: 'Pottery',
    productType: 'Pot',
    images: ['product-pottery-9', 'product-pottery-10'],
    description: 'A traditional earthenware pot for slow-cooking. Its porous nature allows heat and moisture to circulate, resulting in tender, flavorful dishes.',
    makingProcess: 'Local earthenware clay is shaped on a potter\'s wheel. The pot is then burnished for a smooth surface and fired at a low temperature, which retains its natural porosity.',
    region: 'Tamil Nadu',
    material: 'Earthenware clay',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-18',
    name: 'Teak Wood Cutting Board',
    artisanId: 'artisan-7',
    price: 2400,
    category: 'Woodwork',
    productType: 'Cutting Board',
    images: ['product-woodwork-9', 'product-woodwork-10'],
    description: 'A durable and beautiful cutting board made from a single piece of Teak wood. Its natural oils make it resistant to moisture and bacteria.',
    makingProcess: 'A thick slab of sustainably sourced Teak wood is cut to size, sanded smooth, and finished with food-safe mineral oil and beeswax to protect the wood and highlight its grain.',
    region: 'Madhya Pradesh',
    material: 'Teak',
    sustainability: 'Sustainably Sourced',
  },
  {
    id: 'prod-19',
    name: 'Jute Wall Hanging',
    artisanId: 'artisan-4',
    price: 1900,
    category: 'Textiles',
    productType: 'Wall Hanging',
    images: ['product-textiles-9', 'product-textiles-10'],
    description: 'A rustic and eco-friendly wall hanging made from hand-woven jute fibers. This piece of macrame art adds a touch of bohemian charm to any room.',
    makingProcess: 'Natural jute fibers are spun into yarn and then hand-knotted and woven into intricate patterns. The piece is often adorned with wooden beads or other natural elements.',
    region: 'Bihar',
    material: 'Jute',
    sustainability: 'Eco-Friendly',
  },
  {
    id: 'prod-20',
    name: 'Mixed Alloy Tribal Ring',
    artisanId: 'artisan-3',
    price: 1200,
    category: 'Jewelry',
    productType: 'Ring',
    images: ['product-jewelry-9', 'product-jewelry-10'],
    description: 'A bold, adjustable ring made from a mix of alloys, featuring a traditional tribal design. A statement piece that is both rustic and eye-catching.',
    makingProcess: 'Various metal alloys are melted and cast into a mold. The ring is then hand-finished, with details hammered and oxidized to give it an antique, tribal look.',
    region: 'Nagaland',
    material: 'Mixed alloys',
    sustainability: 'Recycled Materials',
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    reviewer: 'Jane D.',
    rating: 5,
    comment: 'Absolutely gorgeous vase! The craftsmanship is incredible. It looks even better in person.',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    reviewer: 'Mark T.',
    rating: 4,
    comment: 'Beautiful piece, but a bit smaller than I expected. Still, the quality is top-notch.',
  },
  {
    id: 'rev-3',
    productId: 'prod-2',
    reviewer: 'Sarah L.',
    rating: 5,
    comment: "This bowl is a work of art. The wood grain is stunning. I almost don't want to use it!",
  },
    {
    id: 'rev-4',
    productId: 'prod-3',
    reviewer: 'Chen W.',
    rating: 5,
    comment: 'So delicate and beautiful. I get compliments every time I wear it. My new favorite necklace.',
  },
];

export const getArtisan = (id: string) => artisans.find(a => a.id === id);
export const getProduct = (id: string) => products.find(p => p.id === id);
export const getReviewsForProduct = (productId: string) => reviews.filter(r => r.productId === productId);
export const getProductsByArtisan = (artisanId: string) => products.filter(p => p.artisanId === artisanId);
