// This is an autogenerated file from Firebase Studio.
// Import the functions you need from the SDKs you need
import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";

// Your web app's Firebase configuration is provided by the backend
// It's safe to expose this configuration to the client
const firebaseConfig = {
  "projectId": "studio-5265999648-36a21",
  "appId": "1:1024891033271:web:affd938c03d7adc8671f32",
  "storageBucket": "studio-5265999648-36a21.appspot.com",
  "apiKey": "AIzaSyAKGpYIeuk4Yg8Ad9VYlzq6GeVA--sfVks",
  "authDomain": "studio-5265999648-36a21.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1024891033271"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

export const auth = getAuth(app);
