// This is an autogenerated file from Firebase Studio.
"use client";

import React, { createContext, useState, useEffect, useCallback } from "react";

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  translate: (text: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Placeholder for real translations
const translations: Record<string, Record<string, string>> = {
  hi: {
    "Home": "होम",
    "Marketplace": "बाजार",
    "Artisans": "कारीगर",
    "Story Map": "कहानी का नक्शा",
    "Workshops": "कार्यशालाएं",
    "Community": "समुदाय",
    "Login": "लॉग इन करें",
    "Sign Up": "साइन अप करें",
    "About Artisan Alley": "आर्टिसन एले के बारे में",
    "Connecting Cultures, Empowering Artisans, and Redefining Craftsmanship through Technology.": "संस्कृतियों को जोड़ना, कारीगरों को सशक्त बनाना, और प्रौद्योगिकी के माध्यम से शिल्प कौशल को फिर से परिभाषित करना।",
    "Our Mission": "हमारा लक्ष्य",
    "Artisan Alley was born from a desire to preserve and celebrate cultural heritage in a rapidly modernizing world. Our mission is to build a global community where technology empowers, rather than replaces, traditional craftsmanship. We provide a platform for artisans to share their stories, showcase their skills, and reach a global audience, ensuring their timeless traditions thrive for generations to come. Every purchase on Artisan Alley is a direct investment in an artisan's livelihood and the preservation of their culture.": "आर्टिसन एले का जन्म तेजी से आधुनिकीकरण की दुनिया में सांस्कृतिक विरासत को संरक्षित और मनाने की इच्छा से हुआ था। हमारा मिशन एक वैश्विक समुदाय का निर्माण करना है जहां प्रौद्योगिकी पारंपरिक शिल्प कौशल को बदलने के बजाय सशक्त बनाती है। हम कारीगरों को अपनी कहानियों को साझा करने, अपने कौशल का प्रदर्शन करने और वैश्विक दर्शकों तक पहुंचने के लिए एक मंच प्रदान करते हैं, यह सुनिश्चित करते हुए कि उनकी कालातीत परंपराएं आने वाली पीढ़ियों के लिए फलती-फूलती रहें। आर्टिसन एले पर हर खरीद एक कारीगर की आजीविका और उनकी संस्कृति के संरक्षण में एक सीधा निवेश है।",
    "What Makes Us Unique": "हमें क्या खास बनाता है",
    "AI-Powered Discovery": "AI-संचालित खोज",
    "Our advanced AI algorithms learn your unique taste to provide personalized product recommendations, helping you discover treasures you'll truly love.": "हमारे उन्नत AI एल्गोरिदम आपकी अनूठी पसंद को सीखते हैं ताकि व्यक्तिगत उत्पाद सिफारिशें प्रदान की जा सकें, जिससे आपको ऐसे खजाने खोजने में मदद मिलती है जिन्हें आप वास्तव में पसंद करेंगे।",
    "AR Virtual Try-On": "AR वर्चुअल ट्राई-ऑन",
    "Visualize how products will look in your space or on you with our cutting-edge Augmented Reality feature, bridging the gap between online shopping and real-life experience.": "हमारे अत्याधुनिक ऑगमेंटेड रियलिटी फीचर के साथ कल्पना करें कि उत्पाद आपके स्थान पर या आप पर कैसे दिखेंगे, जो ऑनलाइन शॉपिंग और वास्तविक जीवन के अनुभव के बीच की खाई को पाटता है।",
    "Cultural Storytelling Map": "सांस्कृतिक कहानी सुनाने का नक्शा",
    "Embark on a journey across the globe with our interactive map. Explore the origins of crafts and connect with the stories and cultures behind each piece.": "हमारे इंटरेक्टिव मानचित्र के साथ दुनिया भर की यात्रा पर निकलें। शिल्प की उत्पत्ति का अन्वेषण करें और प्रत्येक टुकड़े के पीछे की कहानियों और संस्कृतियों से जुड़ें।",
    "How It Works": "यह कैसे काम करता है",
    "For Customers": "ग्राहकों के लिए",
    "Using Artisan Alley is simple. Browse our curated Marketplace, explore artisan profiles, and use our AI tools to find pieces that resonate with you. Add items to your cart, proceed to a secure checkout, and receive a handcrafted treasure at your doorstep. You're not just buying an item; you're acquiring a piece of art with a story, and directly supporting the artisan who made it.": "आर्टिसन एले का उपयोग करना सरल है। हमारे क्यूरेटेड मार्केटप्लेस को ब्राउज़ करें, कारीगर प्रोफाइल का अन्वेषण करें, और उन टुकड़ों को खोजने के लिए हमारे AI टूल का उपयोग करें जो आपके साथ प्रतिध्वनित होते हैं। अपने कार्ट में आइटम जोड़ें, एक सुरक्षित चेकआउट के लिए आगे बढ़ें, और अपने दरवाजे पर एक दस्तकारी खजाना प्राप्त करें। आप सिर्फ एक आइटम नहीं खरीद रहे हैं; आप एक कहानी के साथ कला का एक टुकड़ा प्राप्त कर रहे हैं, और इसे बनाने वाले कारीगर का सीधे समर्थन कर रहे हैं।",
    "For Artisans": "कारीगरों के लिए",
    "We provide a free, easy-to-use platform for artisans to create their digital storefront. Our AI tools assist with writing product descriptions and reaching the right audience. We handle the complexities of e-commerce, from secure payments to global shipping logistics, so you can focus on what you do best: creating. Join our community to share your craft, grow your business, and preserve your cultural legacy.": "हम कारीगरों को अपना डिजिटल स्टोरफ्रंट बनाने के लिए एक मुफ्त, उपयोग में आसान मंच प्रदान करते हैं। हमारे AI उपकरण उत्पाद विवरण लिखने और सही दर्शकों तक पहुंचने में सहायता करते हैं। हम सुरक्षित भुगतान से लेकर वैश्विक शिपिंग लॉजिस्टिक्स तक, ई-कॉमर्स की जटिलताओं को संभालते हैं, ताकि आप उस पर ध्यान केंद्रित कर सकें जो आप सबसे अच्छा करते हैं: बनाना। अपने शिल्प को साझा करने, अपना व्यवसाय बढ़ाने और अपनी सांस्कृतिक विरासत को संरक्षित करने के लिए हमारे समुदाय में शामिल हों।",
    "Meet Our Artisans": "हमारे कारीगरों से मिलें",
    "The heart and soul behind every handcrafted piece.": "हर दस्तकारी कृति के पीछे दिल और आत्मा।",
    "Your Cart": "आपकी गाड़ी",
    "Items": "आइटम",
    "Clear Cart": "कार्ट साफ़ करें",
    "Order Summary": "आदेश सारांश",
    "Subtotal": "उप-योग",
    "Shipping": "शिपिंग",
    "Total": "कुल",
    "Calculated at next step": "अगले चरण में गणना की गई",
    "Proceed to Checkout": "चेकआउट के लिए आगे बढ़ें",
    "Your cart is empty": "आपकी खरीदारी की गाड़ी खाली है",
    "Looks like you haven't added anything to your cart yet.": "लगता है आपने अभी तक अपनी कार्ट में कुछ भी नहीं जोड़ा है।",
    "Start Shopping": "खरीदारी शुरू करें",
    "All Products": "सभी उत्पाद",
    "Browse our entire collection of handcrafted treasures.": "हमारे दस्तकारी खजाने के पूरे संग्रह को ब्राउज़ करें।",
    "Jewelry": "आभूषण",
    "Explore exquisite, handcrafted jewelry.": "उत्तम, दस्तकारी वाले आभूषणों का अन्वेषण करें।",
    "Pottery": "मिट्टी के बर्तन",
    "Discover handcrafted pottery from skilled artisans.": "कुशल कारीगरों से दस्तकारी मिट्टी के बर्तनों की खोज करें।",
    "Textiles": "वस्त्र",
    "Explore hand-woven and embroidered textiles.": "हाथ से बुने और कढ़ाई वाले वस्त्रों का अन्वेषण करें।",
    "Woodwork": "लकड़ी का काम",
    "Discover beautifully crafted wooden items.": "खूबसूरती से तैयार की गई लकड़ी की वस्तुओं की खोज करें।",
    "Checkout": "चेक आउट",
    "Shipping Information": "शिपिंग सूचना",
    "First Name": "पहला नाम",
    "John": "जॉन",
    "Last Name": "अंतिम नाम",
    "Doe": "डो",
    "Address": "पता",
    "City": "शहर",
    "ZIP Code": "ज़िप कोड",
    "Payment": "भुगतान",
    "Card Number": "कार्ड नंबर",
    "Expiry": "समाप्ति",
    "CVC": "सीवीसी",
    "Pay": "भुगतान करें",
    "Add a tip to support the artisan directly": "कारीगर को सीधे समर्थन देने के लिए एक टिप जोड़ें",
    "Custom": "कस्टम",
    "Thank You!": "धन्यवाद!",
    "Your order has been placed successfully.": "आपका ऑर्डर सफलतापूर्वक रखा गया है।",
    "A Note from the Artisan": "कारीगर से एक नोट",
    "\"Thank you for your support! Each purchase helps me continue my craft and share my passion with the world. I hope you love your new piece as much as I loved creating it.\"": "\"आपके समर्थन के लिए धन्यवाद! प्रत्येक खरीद मुझे अपना शिल्प जारी रखने और दुनिया के साथ अपने जुनून को साझा करने में मदद करती है। मुझे उम्मीद है कि आप अपने नए टुकड़े को उतना ही पसंद करेंगे जितना मैंने इसे बनाने में पसंद किया।\"",
    "Continue Shopping": "खरीदारी जारी रखें",
    "From Our Community": "हमारे समुदाय से",
    "See how our handcrafted treasures are woven into the lives of our customers.": "देखें कि हमारे दस्तकारी खजाने हमारे ग्राहकों के जीवन में कैसे बुने जाते हैं।",
    "Share Your Story": "अपनी कहानी साझा करें",
    "Cultural Heritage Stories": "सांस्कृतिक विरासत की कहानियाँ",
    "Explore the origins and stories behind the crafts.": "शिल्प के पीछे की उत्पत्ति और कहानियों का अन्वेषण करें।",
    "The Zapotec Pottery of Oaxaca": "ओक्साका की जैपोटेक पॉटरी",
    "Discover the ancient techniques of Zapotec pottery, a tradition passed down through generations in the valleys of Oaxaca. Each piece is shaped by hand and fired in open-air pits, embedding the spirit of the earth into the clay.": "जैपोटेक पॉटरी की प्राचीन तकनीकों की खोज करें, जो ओक्साका की घाटियों में पीढ़ियों से चली आ रही एक परंपरा है। प्रत्येक टुकड़ा हाथ से आकार दिया जाता है और खुली हवा के गड्ढों में पकाया जाता है, जो पृथ्वी की आत्मा को मिट्टी में समाहित करता है।",
    "Appalachian Woodworking": "एपलाचियन वुडवर्किंग",
    "In the heart of the Appalachian mountains, artisans transform native hardwoods into functional art. This tradition honors the natural beauty of the wood, celebrating simplicity, craftsmanship, and a deep connection to the forest.": "एपलाचियन पहाड़ों के केंद्र में, कारीगर देशी दृढ़ लकड़ी को कार्यात्मक कला में बदलते हैं। यह परंपरा लकड़ी की प्राकृतिक सुंदरता का सम्मान करती है, सादगी, शिल्प कौशल और जंगल से गहरे संबंध का जश्न मनाती है।",
    "The Art of Kundan in Jaipur": "जयपुर में कुंदन की कला",
    "Jaipur, the 'Pink City', is home to the royal art of Kundan jewelry. This intricate method involves setting polished gemstones into a gold foil base, creating pieces of breathtaking beauty that once adorned royalty.": "जयपुर, 'गुलाबी शहर', कुंदन आभूषणों की शाही कला का घर है। इस जटिल विधि में पॉलिश किए गए रत्नों को सोने की पन्नी के आधार में स्थापित करना शामिल है, जो लुभावनी सुंदरता के टुकड़े बनाते हैं जो कभी रॉयल्टी को सुशोभित करते थे।",
    "Japanese Kintsugi": "जापानी किंटसुगी",
    "Kintsugi, or 'golden joinery', is the Japanese art of repairing broken pottery with lacquer dusted or mixed with powdered gold, silver, or platinum. It treats breakage and repair as part of the history of an object, rather than something to disguise.": "किंटसुगी, या 'गोल्डन जॉइनरी', टूटे हुए मिट्टी के बर्तनों को पाउडर सोने, चांदी या प्लैटिनम के साथ धूल या मिश्रित लाख के साथ सुधारने की जापानी कला है। यह टूटने और मरम्मत को किसी वस्तु के इतिहास का हिस्सा मानता है, न कि छिपाने के लिए कुछ।",
    "Moroccan Zellige Tilework": "मोरक्कन ज़ेलिज टाइलवर्क",
    "Zellige is a style of mosaic tilework made from individually chiseled geometric tiles set into a plaster base. This art form is one of the main characteristics of Moroccan architecture and is used to ornament walls, ceilings, and floors.": "ज़ेलिज मोज़ेक टाइलवर्क की एक शैली है जो व्यक्तिगत रूप से छेनी गई ज्यामितीय टाइलों से बनी होती है जो प्लास्टर बेस में सेट होती है। यह कला रूप मोरक्कन वास्तुकला की मुख्य विशेषताओं में से एक है और इसका उपयोग दीवारों, छतों और फर्शों को सजाने के लिए किया जाता है।",
    "Peruvian Retablos": "पेरूवियन रेटब्लोस",
    "Peruvian retablos are intricate, portable shrines holding detailed miniature scenes of religious, historical, or everyday events. These colorful dioramas are a vibrant form of Andean folk art, passed down through families.": "पेरूवियन रेटब्लोस जटिल, पोर्टेबल मंदिर हैं जो धार्मिक, ऐतिहासिक या रोजमर्रा की घटनाओं के विस्तृत लघु दृश्यों को रखते हैं। ये रंगीन डायोरमा एंडियन लोक कला का एक जीवंत रूप हैं, जो परिवारों के माध्यम से पारित किए गए हैं।",
    "Find your next handcrafted treasure. Use the filters to start exploring.": "अपना अगला दस्तकारी खजाना खोजें। खोज शुरू करने के लिए फ़िल्टर का उपयोग करें।",
    "Featured Products": "विशेष रुप से प्रदर्शित उत्पाद",
    "Discover Handcrafted Treasures": "दस्तकारी खजाने की खोज करें",
    "Explore unique creations from artisans worldwide, with personalized recommendations just for you.": "दुनिया भर के कारीगरों से अनूठी कृतियों का अन्वेषण करें, केवल आपके लिए व्यक्तिगत सिफारिशों के साथ।",
    "Explore Crafts": "शिल्प का अन्वेषण करें",
    "Meet Artisans": "कारीगरों से मिलें",
    "Featured Categories": "विशेष रुप से प्रदर्शित श्रेणियां",
    "Artisan of the Month": "महीने का कारीगर",
    "Every purchase directly supports artisans & preserves culture": "प्रत्येक खरीद सीधे कारीगरों का समर्थन करती है और संस्कृति को संरक्षित करती है",
    "by": "द्वारा",
    "reviews": "समीक्षाएं",
    "Wishlist": "इच्छा-सूची",
    "AR Try-On": "AR ट्राई-ऑन",
    "View Profile": "प्रोफ़ाइल देखें",
    "Description": "विवरण",
    "Making Process": "बनाने की प्रक्रिया",
    "Reviews": "समीक्षाएं",
    "No reviews yet.": "अभी तक कोई समीक्षा नहीं।",
    "Your Wishlist": "आपकी इच्छा-सूची",
    "You have": "आपके पास हैं",
    "item": "आइटम",
    "items": "आइटम",
    "in your wishlist.": "आपकी इच्छा-सूची में।",
    "Your wishlist is empty": "आपकी इच्छा-सूची खाली है",
    "Looks like you haven't added anything to your wishlist yet.": "लगता है आपने अभी तक अपनी इच्छा-सूची में कुछ भी नहीं जोड़ा है।",
    "Start Discovering": "खोज शुरू करें",
    "Interactive Workshops": "इंटरैक्टिव कार्यशालाएं",
    "Learn timeless crafts directly from master artisans.": "मास्टर कारीगरों से सीधे कालातीत शिल्प सीखें।",
    "Led by": "के नेतृत्व में",
    "Available Worldwide": "दुनिया भर में उपलब्ध",
    "View Workshop": "कार्यशाला देखें",
    "Add to Cart": "कार्ट में डालें",
    "Add to wishlist": "इच्छा-सूची में जोड़ें",
    "Shopping Cart": "शॉपिंग कार्ट",
    "Open cart": "कार्ट खोलें",
    "View Cart": "कार्ट देखें",
    "Your cart is empty.": "आपकी खरीदारी की गाड़ी खाली है।",
    "Filters": "फ़िल्टर",
    "Category": "श्रेणी",
    "Product Type": "उत्पाद प्रकार",
    "Price Range": "मूल्य सीमा",
    "Region": "क्षेत्र",
    "Material": "सामग्री",
    "Apply Filters": "फ़िल्टर लागू करें",
    "No products found.": "कोई उत्पाद नहीं मिला।",
    "AI Narration Mode": "AI कथन मोड",
    "Narrate Description": "विवरण सुनाएं",
    "Narration Failed": "कथन विफल",
    "Could not generate audio at this time. Please try again later.": "इस समय ऑडियो उत्पन्न नहीं किया जा सका। कृपया बाद में पुन: प्रयास करें।",
    "Your browser does not support the audio element.": "आपका ब्राउज़र ऑडियो तत्व का समर्थन नहीं करता है।",
    "Story": "कहानी",
    "Fun Fact": "मजेदार तथ्य",
    "Culture": "संस्कृति",
    "You Might Also Like": "आपको यह भी पसंद आ सकता हैं",
    "Loading recommendations...": "सिफारिशें लोड हो रही हैं...",
    "Open search": "खोज खोलें",
    "Search for Crafts": "शिल्प के लिए खोजें",
    "Search by product, artisan, or style...": "उत्पाद, कारीगर, या शैली द्वारा खोजें...",
    "Search by voice": "आवाज से खोजें",
    "Search by image": "छवि द्वारा खोजें",
    "Camera Access Required": "कैमरा एक्सेस आवश्यक",
    "Please allow camera access in your browser to use image search. You may need to refresh the page after granting permission.": "छवि खोज का उपयोग करने के लिए कृपया अपने ब्राउज़र में कैमरा एक्सेस की अनुमति दें। अनुमति देने के बाद आपको पृष्ठ को ताज़ा करने की आवश्यकता हो सकती है।",
    "Search with this image": "इस छवि के साथ खोजें",
    "Retake": "पुन: लें",
    "Capture Image": "छवि कैप्चर करें",
    "Back to text search": "पाठ खोज पर वापस जाएं",
    "Hi, I'm Craft Buddy! How can I help you today? You can ask me for gift ideas, product suggestions, or about the history of a craft.": "नमस्ते, मैं क्राफ्ट बडी हूँ! आज मैं आपकी कैसे मदद कर सकता हूँ? आप मुझसे उपहार विचारों, उत्पाद सुझावों, या किसी शिल्प के इतिहास के बारे में पूछ सकते हैं।",
    "Sorry, I'm having a little trouble right now. Please try again later.": "क्षमा करें, मुझे अभी थोड़ी परेशानी हो रही है। कृपया बाद में पुन: प्रयास करें।",
    "Craft Buddy": "क्राफ्ट बडी",
    "Ask me anything...": "मुझसे कुछ भी पूछो...",
    "Eco-Friendly": "पर्यावरण के अनुकूल",
    "Recycled Materials": "पुनर्नवीनीकरण सामग्री",
    "Sustainably Sourced": "स्थायी रूप से स्रोत",
    "A stunning blue pottery vase from Jaipur, hand-painted with traditional floral motifs. A perfect centerpiece that brings a touch of Rajasthani royalty to your home.": "जयपुर का एक शानदार नीला मिट्टी का फूलदान, पारंपरिक पुष्प रूपांकनों से हाथ से पेंट किया गया। एक आदर्श केंद्रबिंदु जो आपके घर में राजस्थानी रॉयल्टी का स्पर्श लाता है।",
    "Crafted from a unique mix of quartz stone powder, powdered glass, and fuller's earth. The iconic cobalt blue dye is used for the vibrant coloring before it is low-fired.": "क्वार्ट्ज पत्थर पाउडर, पाउडर ग्लास और मुल्तानी मिट्टी के एक अनूठे मिश्रण से तैयार किया गया। प्रतिष्ठित कोबाल्ट नीला डाई का उपयोग कम-आग लगाने से पहले जीवंत रंग के लिए किया जाता है।",
    "A hand-carved spice box made from durable Sheesham wood (Indian Rosewood). Features intricate carvings and a rotating lid, making it both a functional kitchen tool and a decorative piece.": "टिकाऊ शीशम की लकड़ी (भारतीय रोज़वुड) से बना एक हाथ से नक्काशीदार मसाला बॉक्स। इसमें जटिल नक्काशी और एक घूमने वाला ढक्कन है, जो इसे एक कार्यात्मक रसोई उपकरण और एक सजावटी टुकड़ा दोनों बनाता है।",
    "A single block of Sheesham wood is selected and meticulously hand-carved by skilled artisans. The piece is then sanded for a smooth finish and polished with natural oils to bring out the rich grain of the wood.": "शीशम की लकड़ी का एक ही ब्लॉक चुना जाता है और कुशल कारीगरों द्वारा सावधानीपूर्वक हाथ से नक्काशी की जाती है। फिर टुकड़े को एक चिकनी फिनिश के लिए रेत दिया जाता है और लकड़ी के समृद्ध दाने को बाहर लाने के लिए प्राकृतिक तेलों से पॉलिश किया जाता है।",
    "From the ghats of Varanasi, Riya Sharma weaves magic into silk sarees. A tradition passed down through generations, her Banarasi sarees are known for their intricate brocades and fine silk.": "वाराणसी के घाटों से, रिया शर्मा रेशम की साड़ियों में जादू बुनती हैं। पीढ़ियों से चली आ रही एक परंपरा, उनकी बनारसी साड़ियाँ अपनी जटिल ब्रोकेड और महीन रेशम के लिए जानी जाती हैं।",
    "Arjun Singh is a master of miniature painting, a delicate art form that flourished in the royal courts of Rajasthan. His works depict epic tales and courtly life with mineral and vegetable-based colors on paper.": "अर्जुन सिंह लघु चित्रकला के उस्ताद हैं, जो राजस्थान के शाही दरबारों में फली-फूली एक नाजुक कला है। उनकी कृतियाँ कागज पर खनिज और वनस्पति-आधारित रंगों के साथ महाकाव्य की कहानियों और दरबारी जीवन को दर्शाती हैं।",
    "Priya is a master of Kundan jewelry, a traditional form of Indian gemstone jewelry. Her intricate designs blend royal heritage with contemporary aesthetics, creating heirloom pieces that are both bold and elegant.": "प्रिया कुंदन आभूषणों की उस्ताद हैं, जो भारतीय रत्न आभूषणों का एक पारंपरिक रूप है। उनके जटिल डिजाइन शाही विरासत को समकालीन सौंदर्यशास्त्र के साथ मिलाते हैं, जो बोल्ड और सुरुचिपूर्ण दोनों तरह के विरासत के टुकड़े बनाते हैं।",
    "Meera Desai is an expert in Bandhani, a traditional tie-dye textile. Her vibrant sarees and dupattas, created by plucking the cloth with the fingernails into many tiny bindings, are a celebration of Gujarati culture.": "मीरा देसाई बंधनी में एक विशेषज्ञ हैं, जो एक पारंपरिक टाई-डाई कपड़ा है। उनकी जीवंत साड़ियाँ और दुपट्टे, कपड़े को नाखूनों से कई छोटे बंधनों में तोड़कर बनाए गए, गुजराती संस्कृति का उत्सव हैं।",
    "Sameer Khan continues the legacy of Kashmiri Pashmina weaving. His shawls, known for their softness and intricate Sozni embroidery, are a testament to the timeless craftsmanship of the valley.": "समीर खान कश्मीरी पश्मीना बुनाई की विरासत को जारी रखते हैं। उनकी शॉल, जो अपनी कोमलता और जटिल सोज़नी कढ़ाई के लिए जानी जाती हैं, घाटी के कालातीत शिल्प कौशल का एक वसीयतनामा हैं।",
    "Anjali Devi is a skilled artisan of Terracotta pottery from the heart of West Bengal. She molds river clay into beautiful sculptures and potteries, reflecting the folk traditions of her region.": "अंजलि देवी पश्चिम बंगाल के केंद्र से टेराकोटा मिट्टी के बर्तनों की एक कुशल कारीगर हैं। वह नदी की मिट्टी को सुंदर मूर्तियों और मिट्टी के बर्तनों में ढालती हैं, जो उनके क्षेत्र की लोक परंपराओं को दर्शाती हैं।",
    "Vikram carries on the 200-year-old tradition of Channapatna toys, a unique form of woodworking using soft ivory wood and vibrant, non-toxic lacquer.": "विक्रम चन्नपटना खिलौनों की 200 साल पुरानी परंपरा को आगे बढ़ाते हैं, जो नरम हाथीदांत की लकड़ी और जीवंत, गैर-विषाक्त लाख का उपयोग करके लकड़ी के काम का एक अनूठा रूप है।",
    "Fatima is a master of Chikankari, the delicate and artfully done hand embroidery from Lucknow. Her ethereal creations on fine cotton and muslin are sought after for their elegance.": "फातिमा चिकनकारी की उस्ताद हैं, जो लखनऊ से नाजुक और कलात्मक रूप से की गई हाथ की कढ़ाई है। महीन कपास और मलमल पर उनकी अलौकिक रचनाएँ उनकी सुंदरता के लिए मांगी जाती हैं।",
    "Welcome back": "वापसी पर स्वागत है",
    "Here's a quick overview of your artisan dashboard.": "यहाँ आपके कारीगर डैशबोर्ड का एक त्वरित अवलोकन है।",
    "Total Revenue": "कुल राजस्व",
    "+20.1% from last month": "पिछले महीने से +20.1%",
    "Orders": "आदेश",
    "+180.1% from last month": "पिछले महीने से +180.1%",
    "Active Listings": "सक्रिय लिस्टिंग",
    "Manage your products": "अपने उत्पादों का प्रबंधन करें",
    "New Feature": "नया फ़ीचर",
    "Add New Product": "नया उत्पाद जोड़ें",
    "Use AI to generate descriptions!": "विवरण उत्पन्न करने के लिए AI का उपयोग करें!",
    "Recent Orders": "हाल के आदेश",
    "No recent orders. Your dashboard will update as you receive new sales.": "कोई हाल का आदेश नहीं। जैसे ही आपको नई बिक्री प्राप्त होगी आपका डैशबोर्ड अपडेट हो जाएगा।",
    "Products": "उत्पादों",
    "Add Product": "उत्पाद जोड़ें",
    "Your Product Listings": "आपके उत्पाद लिस्टिंग",
    "This is where you'll manage your products. Add new items to start selling.": "यह वह जगह है जहाँ आप अपने उत्पादों का प्रबंधन करेंगे। बेचना शुरू करने के लिए नए आइटम जोड़ें।",
    "No Products Yet": "अभी तक कोई उत्पाद नहीं",
    "Start by adding your first product.": "अपना पहला उत्पाद जोड़कर शुरू करें।",
    "Add Your First Product": "अपना पहला उत्पाद जोड़ें",
    "Artisan Settings": "कारीगर सेटिंग्स",
    "Manage your shop and personal information.": "अपनी दुकान और व्यक्तिगत जानकारी प्रबंधित करें।",
    "Profile Information": "प्रोफ़ाइल जानकारी",
    "This is your public artisan name and contact email.": "यह आपका सार्वजनिक कारीगर नाम और संपर्क ईमेल है।",
    "Artisan/Shop Name": "कारीगर/दुकान का नाम",
    "Email Address": "ईमेल पता",
    "Save Changes": "परिवर्तनों को सहेजें",
    "Welcome Back": "वापसी पर स्वागत है",
    "Choose your preferred login method.": "अपनी पसंदीदा लॉगिन विधि चुनें।",
    "Email": "ईमेल",
    "Phone": "फ़ोन",
    "Password": "पासवर्ड",
    "Forgot your password?": "अपना पासवर्ड भूल गए?",
    "Login with Email": "ईमेल से लॉगिन करें",
    "Phone Number": "फ़ोन नंबर",
    "e.g. 5550000000": "उदा. ५५५०००००००",
    "Send One-Time Code": "एक बार का कोड भेजें",
    "One-Time Password": "एक बार का पासवर्ड",
    "Enter your OTP": "अपना OTP दर्ज करें",
    "Login with OTP": "OTP से लॉगिन करें",
    "Or continue with": "या इसके साथ जारी रखें",
    "Login with Google": "Google से लॉगिन करें",
    "Don't have an account?": "खाता नहीं है?",
    "Sign up": "साइन अप करें",
    "customer": "ग्राहक",
    "artisan": "कारीगर",
    "Profile Settings": "प्रोफ़ाइल सेटिंग्स",
    "Account Settings": "खाता सेटिंग्स",
    "About Us": "हमारे बारे में",
    "Switch to": "इसमें स्विच करें",
    "Customer": "ग्राहक",
    "Artisan": "कारीगर",
    "View": "देखें",
    "Contact": "संपर्क",
    "Logout": "लॉग आउट",
    "Delete My Account": "मेरा खाता हटाएं",
    "Are you absolutely sure?": "क्या आप बिल्कुल निश्चित हैं?",
    "This action cannot be undone. This will permanently delete your account and remove your data from our servers.": "यह कार्रवाई पूर्ववत नहीं की जा सकती। यह आपके खाते को स्थायी रूप से हटा देगा और हमारे सर्वर से आपका डेटा हटा देगा।",
    "Cancel": "रद्द करें",
    "Delete": "हटाएं",
    "Logged Out": "लॉग आउट",
    "You have been successfully logged out.": "आप सफलतापूर्वक लॉग आउट हो गए हैं।",
    "Account Deleted": "खाता हटा दिया गया",
    "Your account has been permanently deleted.": "आपका खाता स्थायी रूप से हटा दिया गया है।",
    "Create an Account": "खाता बनाएं",
    "Join our community of artisans and art lovers.": "कारीगरों और कला प्रेमियों के हमारे समुदाय में शामिल हों।",
    "Create Account": "खाता बनाएं",
    "Sign up with Google": "Google से साइन अप करें",
    "Already have an account?": "पहले से ही एक खाता है?",
    "Dashboard": "डैशबोर्ड",
    "Settings": "सेटिंग्स",
    "Analytics": "एनालिटिक्स",
    "Coming Soon!": "जल्द आ रहा है!",
    "We're building powerful analytics to help you understand your customers and grow your business.": "हम आपके ग्राहकों को समझने और आपके व्यवसाय को बढ़ाने में मदद करने के لیے शक्तिशाली एनालिटिक्स बना रहे हैं।",
    "Soon, you'll be able to see top-searched crafts, sales trends, and more.": "जल्द ही, आप शीर्ष-खोजे गए शिल्प, बिक्री के रुझान और बहुत कुछ देख पाएंगे।",
    "Profile Updated": "प्रोफ़ाइल अपडेट की गई",
    "Your profile information has been successfully updated.": "आपकी प्रोफ़ाइल जानकारी सफलतापूर्वक अपडेट कर दी गई है।",
    "Menu": "मेनू",
  },
};


export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState("en");
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    try {
      const localLanguage = localStorage.getItem("language");
      if (localLanguage) {
        setLanguage(localLanguage);
      }
    } catch (error) {
      console.error("Failed to read language from localStorage", error);
    }
  }, []);

  useEffect(() => {
    if (isClient) {
      try {
        localStorage.setItem("language", language);
      } catch (error) {
        console.error("Failed to save language to localStorage", error);
      }
    }
  }, [language, isClient]);

  const translate = useCallback((text: string): string => {
    if (language === 'en' || !text) {
      return text;
    }
    // In a real app, this would call an AI translation flow.
    // For now, it uses a placeholder dictionary.
    return translations[language]?.[text] || text;
  }, [language]);

  const value = {
    language,
    setLanguage,
    translate,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
