// This is an autogenerated file from Firebase Studio.
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PlusCircle } from "lucide-react";
import Link from "next/link";
import { useLanguage } from "@/hooks/use-language";
import { useAuth } from "@/hooks/use-auth";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export default function ProductsPage() {
    const { translate } = useLanguage();
    const { user, isLoggedIn } = useAuth();
    const router = useRouter();

    useEffect(() => {
        if (!isLoggedIn || user?.role !== 'artisan') {
            router.push('/login');
        }
    }, [isLoggedIn, user, router]);

    if (!isLoggedIn || user?.role !== 'artisan') {
        return null;
    }


    return (
        <div className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8">
          <div className="flex items-center">
            <h1 className="font-semibold text-lg md:text-2xl">{translate('Products')}</h1>
            <Button asChild className="ml-auto">
                <Link href="/dashboard/products/new">
                    <PlusCircle className="h-4 w-4 mr-2" />
                    {translate('Add Product')}
                </Link>
            </Button>
          </div>

          <Card>
              <CardHeader>
                  <CardTitle>{translate('Your Product Listings')}</CardTitle>
                  <CardDescription>
                      {translate("This is where you'll manage your products. Add new items to start selling.")}
                  </CardDescription>
              </CardHeader>
              <CardContent>
                  <div className="text-center py-12 border-2 border-dashed rounded-lg">
                      <h3 className="text-xl font-semibold">{translate('No Products Yet')}</h3>
                      <p className="text-muted-foreground mb-4">{translate('Start by adding your first product.')}</p>
                       <Button asChild>
                            <Link href="/dashboard/products/new">
                                <PlusCircle className="h-4 w-4 mr-2" />
                                {translate('Add Your First Product')}
                            </Link>
                        </Button>
                  </div>
              </CardContent>
          </Card>
        </div>
    )
}
