// This is an autogenerated file from Firebase Studio.
'use client';
import Image from 'next/image';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { Gem, Map, Camera, Users, Sparkles, HandHeart } from 'lucide-react';
import { useLanguage } from '@/hooks/use-language';

export default function AboutPage() {
  const { translate } = useLanguage();
  const missionImage = PlaceHolderImages.find(img => img.id === 'hero-background');
  const forCustomersImage = PlaceHolderImages.find(img => img.id === 'product-pottery-1');
  const forArtisansImage = PlaceHolderImages.find(img => img.id === 'artisan-portrait-2');

  return (
    <div className="container mx-auto px-4 py-12 md:px-6">
      <header className="mb-12 text-center">
        <h1 className="font-headline text-5xl font-bold">{translate('About Artisan Alley')}</h1>
        <p className="mt-4 text-xl text-muted-foreground">
          {translate('Connecting Cultures, Empowering Artisans, and Redefining Craftsmanship through Technology.')}
        </p>
      </header>

      <section className="mb-16">
        <Card className="overflow-hidden">
          <div className="grid md:grid-cols-2">
            {missionImage && <div className="relative h-64 md:h-full">
              <Image
                src={missionImage.imageUrl}
                alt="Artisan's workshop"
                fill
                className="object-cover"
                data-ai-hint={missionImage.imageHint}
              />
            </div>}
            <div className="p-8">
              <h2 className="font-headline text-3xl font-semibold">{translate('Our Mission')}</h2>
              <p className="mt-4 text-muted-foreground">
                {translate("Artisan Alley was born from a desire to preserve and celebrate cultural heritage in a rapidly modernizing world. Our mission is to build a global community where technology empowers, rather than replaces, traditional craftsmanship. We provide a platform for artisans to share their stories, showcase their skills, and reach a global audience, ensuring their timeless traditions thrive for generations to come. Every purchase on Artisan Alley is a direct investment in an artisan's livelihood and the preservation of their culture.")}
              </p>
            </div>
          </div>
        </Card>
      </section>

      <section className="mb-16 text-center">
        <h2 className="font-headline text-3xl font-bold mb-8">{translate('What Makes Us Unique')}</h2>
        <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
          <FeatureCard
            icon={<Sparkles className="h-10 w-10 text-primary" />}
            title={translate('AI-Powered Discovery')}
            description={translate("Our advanced AI algorithms learn your unique taste to provide personalized product recommendations, helping you discover treasures you'll truly love.")}
          />
          <FeatureCard
            icon={<Camera className="h-10 w-10 text-primary" />}
            title={translate('AR Virtual Try-On')}
            description={translate("Visualize how products will look in your space or on you with our cutting-edge Augmented Reality feature, bridging the gap between online shopping and real-life experience.")}
          />
          <FeatureCard
            icon={<Map className="h-10 w-10 text-primary" />}
            title={translate('Cultural Storytelling Map')}
            description={translate("Embark on a journey across the globe with our interactive map. Explore the origins of crafts and connect with the stories and cultures behind each piece.")}
          />
        </div>
      </section>

      <section className="mb-16">
        <h2 className="font-headline text-3xl font-bold mb-8 text-center">{translate('How It Works')}</h2>
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
          <Card>
             {forCustomersImage && <div className="relative h-64 w-full">
                 <Image src={forCustomersImage.imageUrl} alt="Customer admiring pottery" fill className="object-cover rounded-t-lg" data-ai-hint={forCustomersImage.imageHint} />
             </div>}
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><Users className="h-6 w-6 text-primary"/>{translate('For Customers')}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                {translate("Using Artisan Alley is simple. Browse our curated Marketplace, explore artisan profiles, and use our AI tools to find pieces that resonate with you. Add items to your cart, proceed to a secure checkout, and receive a handcrafted treasure at your doorstep. You're not just buying an item; you're acquiring a piece of art with a story, and directly supporting the artisan who made it.")}
              </p>
            </CardContent>
          </Card>
          <Card>
            {forArtisansImage && <div className="relative h-64 w-full">
                 <Image src={forArtisansImage.imageUrl} alt="Artisan at work" fill className="object-cover rounded-t-lg" data-ai-hint={forArtisansImage.imageHint} />
            </div>}
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><HandHeart className="h-6 w-6 text-primary"/>{translate('For Artisans')}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                {translate("We provide a free, easy-to-use platform for artisans to create their digital storefront. Our AI tools assist with writing product descriptions and reaching the right audience. We handle the complexities of e-commerce, from secure payments to global shipping logistics, so you can focus on what you do best: creating. Join our community to share your craft, grow your business, and preserve your cultural legacy.")}
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) {
    return (
        <Card className="p-6 text-center">
            <div className="mb-4 inline-block rounded-full bg-primary/10 p-4">
                {icon}
            </div>
            <h3 className="font-headline text-xl font-semibold">{title}</h3>
            <p className="mt-2 text-muted-foreground">{description}</p>
        </Card>
    );
}
