// This is an autogenerated file from Firebase Studio.
"use client"
import { Line, LineChart, XAxis, YAxis } from "recharts"
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart"

const chartData = [
  { month: "January", orders: 186 },
  { month: "February", orders: 305 },
  { month: "March", orders: 237 },
  { month: "April", orders: 273 },
  { month: "May", orders: 209 },
  { month: "June", orders: 414 },
]

const chartConfig = {
  orders: {
    label: "Orders",
    color: "hsl(var(--chart-2))",
  },
}

export function OrdersChart() {
  return (
      <ChartContainer config={chartConfig} className="w-full h-full">
        <LineChart accessibilityLayer data={chartData}>
            <XAxis dataKey="month" tickLine={false} axisLine={false} tickMargin={8} fontSize={12} hide />
            <YAxis tickLine={false} axisLine={false} tickMargin={8} width={30} hide />
            <ChartTooltip content={<ChartTooltipContent hideLabel />} cursor={false}/>
            <Line dataKey="orders" type="monotone" stroke="var(--color-orders)" strokeWidth={2} dot={false}/>
        </LineChart>
      </ChartContainer>
  )
}
