// This is an autogenerated file from Firebase Studio.
"use client"
import { TrendingUp } from "lucide-react"
import { Bar, BarChart, XAxis, YAxis } from "recharts"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart"

const chartData = [
  { month: "January", revenue: 186 },
  { month: "February", revenue: 305 },
  { month: "March", revenue: 237 },
  { month: "April", revenue: 73 },
  { month: "May", revenue: 209 },
  { month: "June", revenue: 214 },
]

const chartConfig = {
  revenue: {
    label: "Revenue",
    color: "hsl(var(--chart-1))",
  },
}

export function RevenueChart() {
  return (
      <ChartContainer config={chartConfig} className="w-full h-full">
        <BarChart accessibilityLayer data={chartData}>
            <XAxis dataKey="month" tickLine={false} axisLine={false} tickMargin={8} fontSize={12} hide />
            <YAxis tickLine={false} axisLine={false} tickMargin={8} width={30} hide/>
            <ChartTooltip content={<ChartTooltipContent hideLabel />} cursor={false}/>
          <Bar dataKey="revenue" fill="var(--color-revenue)" radius={4} />
        </BarChart>
      </ChartContainer>
  )
}
