// This is an autogenerated file from Firebase Studio.
'use client';
import { ProductCard } from "@/components/ProductCard";
import type { Product } from "@/lib/types";
import { useLanguage } from "@/hooks/use-language";

type ProductGridProps = {
  products: Product[];
};

export function ProductGrid({ products }: ProductGridProps) {
  const { translate } = useLanguage();
  if (products.length === 0) {
    return (
      <div className="flex h-64 items-center justify-center">
        <p className="text-muted-foreground">{translate('No products found.')}</p>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {products.map((product) => (
        <ProductCard key={product.id} product={product} />
      ))}
    </div>
  );
}