// This is an autogenerated file from Firebase Studio.
'use client';
import { ArtisanHeader } from './ArtisanHeader';
import { useAuth } from '@/hooks/use-auth';
import Image from 'next/image';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { getArtisan, artisans } from '@/lib/data';
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { Star, Link as LinkIcon, Settings, Bell, MessageSquare } from 'lucide-react';
import Link from 'next/link';

function ArtisanProfileSidebar() {
    const { user } = useAuth();
    // Find an artisan that matches the logged-in user's name or email for demonstration
    const artisan = user ? artisans.find(a => a.email === user.email || a.name === user.name) : null; 
    
    if (!user || !artisan) return null;

    const profileImage = PlaceHolderImages.find(p => p.id === artisan.profileImage);
    const bannerImage = PlaceHolderImages.find(p => p.id === artisan.bannerImage);

    return (
        <aside className="sticky top-0 h-screen w-72 flex-shrink-0 border-r bg-card p-6 hidden lg:flex flex-col">
            <div className="relative h-24 w-full rounded-lg overflow-hidden mb-[-3rem]">
                {bannerImage && <Image src={bannerImage.imageUrl} alt="Store Banner" fill className="object-cover" />}
            </div>
            <div className="flex flex-col items-center text-center">
                 <Avatar className="h-24 w-24 border-4 border-card relative z-10">
                    <AvatarImage src={user.avatar} alt={user.name} />
                    <AvatarFallback>{user.name.charAt(0)}</AvatarFallback>
                </Avatar>
                <h2 className="mt-4 font-headline text-xl font-bold">{user.name}</h2>
                <p className="text-sm text-muted-foreground">{artisan.location}</p>
                <div className="mt-2 flex items-center gap-1 text-yellow-500">
                    <Star className="h-4 w-4 fill-current"/>
                    <Star className="h-4 w-4 fill-current"/>
                    <Star className="h-4 w-4 fill-current"/>
                    <Star className="h-4 w-4 fill-current"/>
                    <Star className="h-4 w-4" />
                    <span className="text-xs text-muted-foreground ml-1">(125 reviews)</span>
                </div>
            </div>
            
            <nav className="mt-8 flex flex-col gap-2">
                <Link href={`/artisans/${artisan.id}`} className="flex items-center gap-2 rounded-md p-2 text-sm font-medium text-muted-foreground hover:bg-secondary hover:text-foreground">
                    <LinkIcon className="h-4 w-4" /> View Storefront
                </Link>
                 <Link href="/dashboard/settings" className="flex items-center gap-2 rounded-md p-2 text-sm font-medium text-muted-foreground hover:bg-secondary hover:text-foreground">
                    <Settings className="h-4 w-4" /> Store Settings
                </Link>
                 <Link href="#" className="flex items-center gap-2 rounded-md p-2 text-sm font-medium text-muted-foreground hover:bg-secondary hover:text-foreground">
                    <Bell className="h-4 w-4" /> Notifications
                </Link>
                <Link href="#" className="flex items-center gap-2 rounded-md p-2 text-sm font-medium text-muted-foreground hover:bg-secondary hover:text-foreground">
                    <MessageSquare className="h-4 w-4" /> Messages
                </Link>
            </nav>

            <div className="mt-auto">
                {/* Footer content for sidebar if needed */}
            </div>
        </aside>
    );
}


export function ArtisanLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen">
      <ArtisanProfileSidebar />
      <div className="flex-1 flex flex-col">
        <ArtisanHeader />
        <main className="flex-1 p-6 md:p-8 bg-secondary/30">{children}</main>
      </div>
    </div>
  );
}
