// This is an autogenerated file from Firebase Studio.
'use client';
import './globals.css';
import { cn } from '@/lib/utils';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Providers } from '@/components/providers';
import { Toaster } from '@/components/ui/toaster';
import { CraftBuddyWidget } from '@/components/CraftBuddyWidget';
import { useAuth } from '@/hooks/use-auth';
import { usePathname } from 'next/navigation';
import { ArtisanLayout } from '@/components/layout/ArtisanLayout';

function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const { user } = useAuth();
    const pathname = usePathname();

    const isDashboard = pathname.startsWith('/dashboard');

    if (isDashboard && user?.role === 'artisan') {
        return <ArtisanLayout>{children}</ArtisanLayout>
    }

    return (
        <div className="flex min-h-screen flex-col">
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
            <CraftBuddyWidget />
        </div>
    )
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={cn(
          'min-h-screen bg-background font-body antialiased'
        )}
      >
        <Providers attribute="class" defaultTheme="system" enableSystem>
            <AppLayout>{children}</AppLayout>
            <Toaster />
        </Providers>
      </body>
    </html>
  );
}
