
// This is an autogenerated file from Firebase Studio.
'use client';
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Container, Gem, LayoutGrid, Axe } from "lucide-react";
import { ArtisanCard } from "@/components/ArtisanCard";
import { artisans } from "@/lib/data";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { useLanguage } from "@/hooks/use-language";

const categories = [
  { name: "Pottery", icon: <Container className="h-8 w-8" />, href: "/marketplace?category=Pottery" },
  { name: "Jewelry", icon: <Gem className="h-8 w-8" />, href: "/marketplace?category=Jewelry" },
  { name: "Textiles", icon: <LayoutGrid className="h-8 w-8" />, href: "/marketplace?category=Textiles" },
  { name: "Woodwork", icon: <Axe className="h-8 w-8" />, href: "/marketplace?category=Woodwork" },
];

export default function Home() {
  const { translate } = useLanguage();
  const featuredArtisan = artisans[0];
  const heroImage = PlaceHolderImages.find(img => img.id === 'hero-background');

  return (
    <div>
      {/* Hero Section */}
      <section className="relative h-[60vh] min-h-[400px] w-full">
        {heroImage && (
             <Image
                src={heroImage.imageUrl}
                alt={heroImage.description}
                fill
                className="object-cover"
                priority
                data-ai-hint={heroImage.imageHint}
            />
        )}
        <div className="absolute inset-0 bg-black/50" />
        <div className="relative z-10 flex h-full flex-col items-center justify-center text-center text-white">
          <h1 className="font-headline text-4xl font-bold md:text-6xl">
            {translate('Discover Handcrafted Treasures')}
          </h1>
          <p className="mt-4 max-w-2xl text-lg text-primary-foreground/90 dark:text-white/90">
            {translate('Explore unique creations from artisans worldwide, with personalized recommendations just for you.')}
          </p>
          <div className="mt-8 flex flex-col gap-4 sm:flex-row">
            <Button size="lg" asChild>
              <Link href="/marketplace">{translate('Explore Crafts')}</Link>
            </Button>
            <Button size="lg" variant="secondary" asChild>
              <Link href="/artisans">{translate('Meet Artisans')}</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Featured Categories */}
      <section className="py-16 sm:py-24">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-12 text-center font-headline text-3xl font-bold">
            {translate('Featured Categories')}
          </h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-8">
            {categories.map((category) => (
              <Link key={category.name} href={category.href}>
                 <Card className="group flex h-full w-full items-center justify-center p-6 text-center transition-all hover:bg-secondary hover:shadow-lg">
                    <CardContent className="flex flex-col items-center justify-center p-0">
                        <div className="mb-4 text-primary transition-transform group-hover:scale-110">
                            {category.icon}
                        </div>
                        <h3 className="font-headline text-xl font-semibold">{translate(category.name)}</h3>
                    </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>
      
      {/* Featured Artisan */}
      <section className="bg-secondary/50 py-16 sm:py-24">
        <div className="container mx-auto px-4 md:px-6">
           <h2 className="mb-12 text-center font-headline text-3xl font-bold">
            {translate('Artisan of the Month')}
          </h2>
          <div className="mx-auto max-w-2xl">
            {featuredArtisan && <ArtisanCard artisan={featuredArtisan} />}
          </div>
        </div>
      </section>

      {/* Impact Banner */}
      <section className="py-12 bg-gradient-to-r from-primary/80 to-accent/80 text-primary-foreground">
          <div className="container mx-auto px-4 md:px-6">
            <p className="text-center text-xl font-semibold">
                {translate('Every purchase directly supports artisans & preserves culture')}
            </p>
          </div>
      </section>
    </div>
  );
}
