// This is an autogenerated file from Firebase Studio.
'use client';
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import type { Artisan } from "@/lib/types";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { useLanguage } from "@/hooks/use-language";

type ArtisanCardProps = {
  artisan: Artisan;
};

export function ArtisanCard({ artisan }: ArtisanCardProps) {
  const { translate } = useLanguage();
  const image = PlaceHolderImages.find((img) => img.id === artisan.profileImage);

  return (
    <Card className="flex flex-col overflow-hidden">
      <CardHeader className="flex flex-row items-center gap-4">
        <div className="relative h-20 w-20 flex-shrink-0">
          {image && (
            <Image
              src={image.imageUrl}
              alt={artisan.name}
              width={80}
              height={80}
              className="rounded-full object-cover"
              data-ai-hint={image.imageHint}
            />
          )}
        </div>
        <div>
            <CardTitle className="font-headline text-2xl">{artisan.name}</CardTitle>
            <CardDescription>{artisan.location}</CardDescription>
        </div>
      </CardHeader>
      <CardContent className="flex-grow">
        <p className="text-muted-foreground line-clamp-3">{translate(artisan.story)}</p>
      </CardContent>
      <CardFooter>
        <Button asChild className="w-full">
          <Link href={`/artisans/${artisan.id}`}>{translate('View Profile')}</Link>
        </Button>
      </CardFooter>
    </Card>
  );
}
