// This is an autogenerated file from Firebase Studio.
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/hooks/use-auth";
import { useToast } from "@/hooks/use-toast";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useLanguage } from "@/hooks/use-language";

export default function ArtisanSettingsPage() {
    const { user, login, isLoggedIn } = useAuth();
    const router = useRouter();
    const { toast } = useToast();
    const { translate } = useLanguage();
    
    const [name, setName] = useState(user?.name || "");
    const [email, setEmail] = useState(user?.email || "");

    useEffect(() => {
        if (!isLoggedIn || user?.role !== 'artisan') {
            router.push('/login');
        }
    }, [isLoggedIn, user, router]);

    useEffect(() => {
        if (user) {
            setName(user.name);
            setEmail(user.email);
        }
    }, [user]);

    const handleSaveChanges = (e: React.FormEvent) => {
        e.preventDefault();
        if (user) {
            const updatedUser = { ...user, name, email };
            login(updatedUser);
            toast({
                title: translate("Profile Updated"),
                description: translate("Your profile information has been successfully updated."),
            });
        }
    };

    if (!user) {
        return null;
    }

    return (
        <div>
            <header className="mb-8">
                <h1 className="font-headline text-3xl font-bold">{translate('Artisan Settings')}</h1>
                <p className="text-muted-foreground">{translate('Manage your shop and personal information.')}</p>
            </header>
            <Card>
                <form onSubmit={handleSaveChanges}>
                     <CardHeader>
                        <CardTitle>{translate('Profile Information')}</CardTitle>
                        <CardDescription>{translate('This is your public artisan name and contact email.')}</CardDescription>
                    </CardHeader>
                    <CardContent className="pt-6 space-y-6">
                        <div className="space-y-2">
                            <Label htmlFor="name">{translate('Artisan/Shop Name')}</Label>
                            <Input id="name" value={name} onChange={(e) => setName(e.target.value)} />
                        </div>
                         <div className="space-y-2">
                            <Label htmlFor="email">{translate('Email Address')}</Label>
                            <Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
                        </div>
                    </CardContent>
                    <CardContent className="flex justify-end">
                        <Button type="submit">{translate('Save Changes')}</Button>
                    </CardContent>
                </form>
            </Card>
        </div>
    );
}
