// This is an autogenerated file from Firebase Studio.
'use client';
import { useAuth } from '@/hooks/use-auth';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { useLanguage } from '@/hooks/use-language';
import { Wallet, Package, List, PlusCircle, PenSquare, Lightbulb, TrendingUp, Leaf, PackageSearch } from 'lucide-react';
import { RevenueChart } from '@/components/charts/revenue-chart';
import { OrdersChart } from '@/components/charts/orders-chart';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';

export default function DashboardPage() {
    const { user, isLoggedIn } = useAuth();
    const { translate } = useLanguage();
    const router = useRouter();

    useEffect(() => {
        if (!isLoggedIn || user?.role !== 'artisan') {
            router.push('/login');
        }
    }, [isLoggedIn, user, router]);

    if (!isLoggedIn || user?.role !== 'artisan') {
        return null; // or a loading spinner
    }
    
    return (
        <div className="space-y-8">
            <header>
                <h1 className="text-3xl font-bold font-headline mb-2">{translate('Welcome back')}, {user?.name}!</h1>
                <p className="text-muted-foreground">{translate("Here's a quick overview of your artisan dashboard.")}</p>
            </header>

             <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                <Card className="shadow-lg hover:shadow-xl transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">{translate('Total Revenue')}</CardTitle>
                        <Wallet className="h-5 w-5 text-muted-foreground"/>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">₹45,231.89</div>
                        <p className="text-xs text-muted-foreground flex items-center gap-1">
                           <Leaf className="h-3 w-3 text-green-500" /> +20.1% {translate('from last month')}
                        </p>
                        <div className="h-24 mt-4">
                            <RevenueChart />
                        </div>
                    </CardContent>
                </Card>
                <Card className="shadow-lg hover:shadow-xl transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">{translate('Orders')}</CardTitle>
                        <Package className="h-5 w-5 text-muted-foreground"/>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">+2350</div>
                        <p className="text-xs text-muted-foreground flex items-center gap-1">
                           <Leaf className="h-3 w-3 text-green-500" /> +180.1% {translate('from last month')}
                        </p>
                         <div className="h-24 mt-4">
                            <OrdersChart />
                        </div>
                    </CardContent>
                </Card>
                <Card className="shadow-lg hover:shadow-xl transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">{translate('Active Listings')}</CardTitle>
                        <List className="h-5 w-5 text-muted-foreground"/>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">12</div>
                        <p className="text-xs text-muted-foreground">{translate('Manage your products')}</p>
                         <div className="mt-4 pt-4">
                            <Button asChild className="w-full">
                               <Link href="/dashboard/products/new"><PlusCircle className="mr-2"/>{translate('Add New Product')}</Link>
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            </div>
            
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2">
                    <Card className="shadow-lg" style={{borderImage: 'url(/torn-paper.svg) 15 stretch'}}>
                        <CardHeader>
                            <CardTitle>{translate('Recent Orders')}</CardTitle>
                        </CardHeader>
                        <CardContent className="text-center py-10">
                             <PackageSearch className="mx-auto h-12 w-12 text-muted-foreground" />
                            <p className="text-muted-foreground mt-4">{translate('No recent orders. Your dashboard will update as you receive new sales.')}</p>
                        </CardContent>
                    </Card>
                </div>
                <div className="space-y-6">
                     <Card className="bg-yellow-50/50 dark:bg-yellow-900/20 shadow-lg">
                         <CardHeader>
                            <CardTitle className="flex items-center gap-2"><Lightbulb className="text-yellow-500" /> {translate('Craft Buddy Tips')}</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p className="text-sm italic">"{translate('Your pottery is trending in Delhi – upload more to boost sales.')}"</p>
                        </CardContent>
                    </Card>
                     <Card className="shadow-lg">
                         <CardHeader>
                            <CardTitle>{translate('Quick Actions')}</CardTitle>
                        </CardHeader>
                        <CardContent className="grid grid-cols-2 gap-4">
                           <Button variant="outline" asChild><Link href="/dashboard/products/new"><PlusCircle /> {translate('New Product')}</Link></Button>
                           <Button variant="outline" asChild><Link href="/dashboard/settings"><PenSquare /> {translate('Edit Profile')}</Link></Button>
                           <Button variant="outline" asChild><Link href="/dashboard/analytics"><TrendingUp /> {translate('Analytics')}</Link></Button>
                           <Button variant="outline" asChild><Link href="#"><Package /> {translate('Orders')}</Link></Button>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    )
}
