// This is an autogenerated file from Firebase Studio.
'use client';
import { artisans } from "@/lib/data";
import { ArtisanCard } from "@/components/ArtisanCard";
import { useLanguage } from "@/hooks/use-language";

export default function ArtisansPage() {
  const { translate } = useLanguage();
  return (
    <div className="container mx-auto px-4 py-8 md:px-6">
      <header className="mb-8 text-center">
        <h1 className="font-headline text-4xl font-bold">{translate('Meet Our Artisans')}</h1>
        <p className="mt-2 text-lg text-muted-foreground">
          {translate('The heart and soul behind every handcrafted piece.')}
        </p>
      </header>
      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        {artisans.map((artisan) => (
          <ArtisanCard key={artisan.id} artisan={artisan} />
        ))}
      </div>
    </div>
  );
}