// This is an autogenerated file from Firebase Studio.
'use client';
import { notFound } from "next/navigation";
import Image from "next/image";
import { getArtisan, getProductsByArtisan } from "@/lib/data";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { Button } from "@/components/ui/button";
import { BadgeCheck, PlayCircle } from "lucide-react";
import { ProductGrid } from "@/components/marketplace/ProductGrid";
import { Badge } from "@/components/ui/badge";
import { useLanguage } from "@/hooks/use-language";

export default function ArtisanProfilePage({
  params,
}: {
  params: { id: string };
}) {
  const { translate } = useLanguage();
  const artisan = getArtisan(params.id);

  if (!artisan) {
    notFound();
  }

  const products = getProductsByArtisan(artisan.id);
  const bannerImage = PlaceHolderImages.find(
    (img) => img.id === artisan.bannerImage
  );
  const profileImage = PlaceHolderImages.find(
    (img) => img.id === artisan.profileImage
  );
  const videoThumbnail = PlaceHolderImages.find(img => img.id === 'behind-the-scenes-video-thumb');

  return (
    <div>
      {/* Banner Section */}
      <section className="relative h-64 w-full">
        {bannerImage && (
          <Image
            src={bannerImage.imageUrl}
            alt={`${artisan.name}'s craft style`}
            fill
            className="object-cover"
            data-ai-hint={bannerImage.imageHint}
          />
        )}
        <div className="absolute inset-0 bg-black/40" />
      </section>

      {/* Profile Header */}
      <section className="container mx-auto -mt-20 px-4 md:px-6">
        <div className="relative rounded-lg bg-card p-6 shadow-lg">
          <div className="flex flex-col items-center gap-6 text-center md:flex-row md:text-left">
            {profileImage && (
              <div className="relative h-32 w-32 flex-shrink-0 rounded-full border-4 border-card">
                <Image
                  src={profileImage.imageUrl}
                  alt={artisan.name}
                  fill
                  className="rounded-full object-cover"
                  data-ai-hint={profileImage.imageHint}
                />
              </div>
            )}
            <div className="flex-grow">
              <div className="flex items-center justify-center gap-2 md:justify-start">
                <h1 className="font-headline text-3xl font-bold">
                  {artisan.name}
                </h1>
                {artisan.verified && (
                  <BadgeCheck className="h-7 w-7 text-blue-500" />
                )}
              </div>
              <p className="mt-1 text-muted-foreground">{artisan.location}</p>
              <div className="mt-4 flex justify-center gap-2 md:justify-start">
                <Button>{translate('Follow')}</Button>
                <Button variant="secondary">{translate('Support')}</Button>
              </div>
            </div>
          </div>
          <div className="mt-6 border-t pt-6">
            <h2 className="font-headline text-xl font-semibold">{translate('Our Story')}</h2>
            <p className="mt-2 text-muted-foreground">{translate(artisan.story)}</p>
          </div>
        </div>
      </section>

      {/* Video Section */}
      <section className="container mx-auto px-4 py-16 md:px-6">
        <h2 className="mb-8 text-center font-headline text-3xl font-bold">
          {translate('Behind the Scenes')}
        </h2>
        <div className="relative mx-auto max-w-4xl aspect-video cursor-pointer overflow-hidden rounded-lg shadow-xl">
          {videoThumbnail && (
            <Image
              src={videoThumbnail.imageUrl}
              alt="Behind the scenes video thumbnail"
              fill
              className="object-cover"
              data-ai-hint={videoThumbnail.imageHint}
            />
          )}
          <div className="absolute inset-0 flex items-center justify-center bg-black/40 transition-colors hover:bg-black/20">
            <PlayCircle className="h-20 w-20 text-white/80" />
          </div>
        </div>
      </section>

      {/* Product Gallery */}
      <section className="bg-secondary/50 py-16">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-8 text-center font-headline text-3xl font-bold">
            {translate(`${artisan.name}'s Crafts`)}
          </h2>
          <ProductGrid products={products} />
        </div>
      </section>
    </div>
  );
}
