// This is an autogenerated file from Firebase Studio.
"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { useLanguage } from "@/hooks/use-language";
import { useAuth } from "@/hooks/use-auth";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export default function AnalyticsPage() {
    const { translate } = useLanguage();
    const { user, isLoggedIn } = useAuth();
    const router = useRouter();

    useEffect(() => {
        if (!isLoggedIn || user?.role !== 'artisan') {
            router.push('/login');
        }
    }, [isLoggedIn, user, router]);

    if (!isLoggedIn || user?.role !== 'artisan') {
        return null;
    }

    return (
        <div>
            <h1 className="text-3xl font-bold font-headline mb-8">{translate('Analytics')}</h1>
            <Card>
                <CardHeader>
                    <CardTitle>{translate('Coming Soon!')}</CardTitle>
                    <CardDescription>
                        {translate("We're building powerful analytics to help you understand your customers and grow your business.")}
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <p>{translate("Soon, you'll be able to see top-searched crafts, sales trends, and more.")}</p>
                </CardContent>
            </Card>
        </div>
    )
}
